version: 2
updates:
  #  uncomment when https://github.com/dependabot/dependabot-core/issues/1865 is resolved
  #  - package-ecosystem: "npm"
  #    directory: "/"
  #    schedule:
  #      interval: "daily"
  #    versioning-strategy: increase
  #
  #    commit-message:
  #      prefix: "fix"
  #      include: "scope"
  #
  #    allow:
  #      - dependency-name: "@stoplight/*" # match all Stoplight deps, regardless of type
  #        dependency-type: "all"
  #      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly" # we do not need to check for devDependencies updates on a daily basis
    versioning-strategy: "increase"

    commit-message:
      prefix: "chore"
      include: "scope"

    allow:
      - dependency-type: "development"
