# https://github.com/stoplightio/spectral/issues/171
swagger: '2.0'

info:
  title: Repro one
  description: Endpoint definition
  version: "1.0.0"
  contact:
    name: toto
host: not-example.com
schemes:
  - https
basePath: /repro/nested/one

paths:
  /test:
    post:
      summary: Gets nothing
      operationId: "17"
      tags: [ one ]
      description: Cf. summary
      parameters:
        - name: body
          description: Content
          in: body
          schema:
            $ref: '#/definitions/TheDefinition'
          required: true
      responses:
        204:
          description: No content
  /test-2:
    post:
      summary: Gets nothing
      operationId: "18"
      tags: [ ]
      description: Cf. summary
      parameters:
        - name: body
          description: test
          in: body
          schema:
            $ref: '#/definitions/TheMissingDefinition'
          required: true
      responses:
        204:
          description: No content
  /test-3:
    post:
      summary: Gets nothing
      operationId: "12"
      tags: [ ]
      description: Cf. summary
      parameters:
        - name: body
          description: test
          in: body
          schema:
            $ref: '#/definitions/TheInvalidDefinition'
          required: true
      responses:
        204:
          description: No content
definitions:
  TheDefinition:
    type: object
    properties:
      email:
        description: Email address.
        example: "toto@toto.com"
        $ref: './schema-ref.yaml#/definitions/email'
  TheMissingDefinition:
    type: object
    properties:
      email:
        description: Email address.
        example: "toto@toto.com"
        $ref: './schema-ref.yaml#/definitions/email-d'
  TheInvalidDefinition:
    type: object
    properties:
      email:
        description: Email address.
        example: "toto@toto.com"
        $ref: './schema-invalid-ref.yaml#/definitions/email'


