export const functions = {
  alphabetical: require('./alphabetical').alphabetical,
  casing: require('./casing').casing,
  enumeration: require('./enumeration').enumeration,
  length: require('./length').length,
  pattern: require('./pattern').pattern,
  falsy: require('./falsy').falsy,
  schema: require('./schema').schema,
  schemaPath: require('./schema-path').schemaPath,
  truthy: require('./truthy').truthy,
  undefined: require('./undefined').undefined,
  xor: require('./xor').xor,
  unreferencedReusableObject: require('./unreferencedReusableObject').unreferencedReusableObject,
  typedEnum: require('./typedEnum').typedEnum,
};
