---
openapi: 3.0.0
info:
  version: 1.0.0
  title: OAS3
  description: lots of text
  contact:
    name: fred
servers:
  - description: thing
    url: http://localhost
paths: {}
tags:
  - name: my-tag
