%YAML 1.2
---
openapi: 3.0.0

info:
  title: Library
  description: Collection of reusable standard definitions.
  version: 2.0.0
paths: {}
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          maxLength: 1
        error_description:
          type: string
          maxLength: 1
        status_code:
          type: string
        test:
          $ref: ./URIError.yaml#/components/schemas/Foo
    NotFound:
      oneOf:
        - $ref: '#/components/schemas/DoesntExist'
        - $ref: '#/components/schemas/JustCantFindIt'
    DoesntExist:
      type: object
      properties:
        id:
          type: string
    JustCantFindIt:
      type: object
      properties:
        name:
          type: string

  responses:
    NotFoundResponse:
      description: Not Found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
      
