name: Auto-Dependabot

on: 
  pull_request:
    branches:
    - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve
      # if: github.actor == 'dependabot-preview[bot]' || github.actor == "dependabot[bot]'
      if: github.actor == 'philsturgeon'
      uses: hmarr/auto-approve-action@v1.0.0
