name: Release Docker Images
on: workflow_dispatch

jobs:
  build-nix-binaries:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.1
    - name: Install ldid
      uses: "./.github/actions/install-ldid"
    - name: Cached dependencies
      uses: "./.github/actions/cached-dependencies"
    - name: Build
      run: yarn build
    - name: Build binary
      uses: "./.github/actions/build-binary"
      with:
        targets: macos-arm64,linux-arm64,alpine-arm64
        bytecode: false
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: nix-binaries
        path: "./packages/cli/binaries"
  build-nix-binaries-x64:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.1
    - name: Install ldid
      uses: "./.github/actions/install-ldid"
    - name: Cached dependencies
      uses: "./.github/actions/cached-dependencies"
    - name: Build
      run: yarn build
    - name: Build binary
      uses: "./.github/actions/build-binary"
      with:
        targets: macos-x64,linux-x64,alpine-x64
        bytecode: false
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: nix-binaries-x64
        path: "./packages/cli/binaries"
  build-windows-binary:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.1
    - name: Cached dependencies
      uses: "./.github/actions/cached-dependencies"
      with:
        install-corepack: true
    - name: Build
      run: yarn build
    - name: Build binary
      uses: "./.github/actions/build-binary"
      with:
        targets: windows
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: windows-binaries
        path: "./packages/cli/binaries"
  upload-artifacts:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
    needs:
    - build-nix-binaries
    - build-nix-binaries-x64
    - build-windows-binary
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: "/tmp/binaries"
        merge-multiple: true
    - name: Download GitHub Release Utility
      run: go install github.com/tcnksm/ghr@v0.18.3
    - name: Publish Release artifacts on GitHub
      run: ghr -t ${GH_TOKEN} -u ${{ github.repository_owner }} -r ${{ github.event.repository.name }} -c ${{ github.sha }} ${{ github.ref_name }} /tmp/binaries
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
  release-docker:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs:
    - upload-artifacts
    steps:
    - uses: actions/checkout@v5.0.1
    - name: set version in package.json
      run: npm --no-git-tag-version --no-commit-hooks -f version from-git
    - name: docker build
      run: |-
        GIT_SHA="${GITHUB_SHA:0:7}"
        docker build . --tag stoplight/spectral:${GIT_SHA}
    - name: docker login
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: |-
        GIT_SHA="${GITHUB_SHA:0:7}"
        FULL_VERSION="${GITHUB_REF_NAME#v}"
        MINOR_VERSION="${FULL_VERSION%.*}"
        MAJOR_VERSION="${MINOR_VERSION%.*}"

        docker tag stoplight/spectral:${GIT_SHA} stoplight/spectral:${FULL_VERSION}
        docker tag stoplight/spectral:${GIT_SHA} stoplight/spectral:${MINOR_VERSION}
        docker tag stoplight/spectral:${GIT_SHA} stoplight/spectral:${MAJOR_VERSION}
        docker tag stoplight/spectral:${GIT_SHA} stoplight/spectral:latest

        docker push stoplight/spectral:${GIT_SHA}
        docker push stoplight/spectral:${FULL_VERSION}
        docker push stoplight/spectral:${MINOR_VERSION}
        docker push stoplight/spectral:${MAJOR_VERSION}
        docker push stoplight/spectral:latest
