name: test-harness
description: 'Run tests.'  
runs:
  using: composite
  steps:
  - name: Compute commit SHAs to be used for caching purposes
    run: |-
      git rev-parse HEAD~1 > /tmp/previous-commit-sha
      git rev-parse HEAD > /tmp/current-commit-sha
    shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
  - name: restore_cache
    uses: actions/cache@v4.3.0
    with:
      key: test-harness-{{ checksum "/tmp/previous-commit-sha" }}-${{ runner.os }}-${{ inputs.node-version }}
      path: |-
        ./.cache/spectral-test-harness
        ./test-harness/tests/
      restore-keys: test-harness-{{ checksum "/tmp/previous-commit-sha" }}-${{ runner.os }}-${{ inputs.node-version }}
  - uses: "./.github/actions/build-binary"
    with:
      targets: "${{ runner.os.os }}"
      node-version: "${{ inputs.node-version }}"
  - name: Run harness tests
    run: yarn test.harness --maxWorkers=3
    shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
  - name: save_cache
    uses: actions/cache@v4.3.0
    if: always()
    with:
      path: |-
        ./.cache/spectral-test-harness
        ./test-harness/tests/
      key: test-harness-{{ checksum "/tmp/current-commit-sha" }}-${{ runner.os }}-${{ inputs.node-version }}